### ISSUE TITLE
Fails to build in google rbe_ubuntu image (default for bazel runs)

### ISSUE THREAD

**Issue by renau** [jmillikin/rules_m4#4]
docker run -it marketplace.gcr.io/google/rbe-ubuntu16-04:latest

install bazel in the image

and then after cloning, bazel test fails

bazel test //...
INFO: Invocation ID: fbb72c51-f511-4c5c-9897-96b122c7ead9
DEBUG: Rule 'io_bazel_rules_m4' modified arguments {"shallow_since": "1548637354 -0800"}
INFO: Analysed 13 targets (35 packages loaded, 1059 targets configured).
INFO: Found 12 targets and 1 test target...
ERROR: /root/.cache/bazel/_bazel_root/3ee255d691f0c03563386d57050f3aa6/external/m4_v1.4.18/bin/BUILD.bazel:1:1: Linking of rule '@m4_v1.4.18//bin:m4' failed (Exit 1) clang failed: error executing command /usr/local/bin/clang -o bazel-out/host/bin/external/m4_v1.4.18/bin/m4 '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/local/bin -Wl,--gc-sections -Wl,-S ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/host/bin/external/m4_v1.4.18/_objs/m4_lib/symtab.o:symtab.c:function symtab_init: error: undefined reference to '__muloti4'
bazel-out/host/bin/external/m4_v1.4.18/_objs/gnulib/clean-temp.o:clean-temp.c:function create_temp_dir: error: undefined reference to '__muloti4'
bazel-out/host/bin/external/m4_v1.4.18/_objs/gnulib/fatal-signal.o:fatal-signal.c:function at_fatal_signal: error: undefined reference to '__muloti4'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: Elapsed time: 11.813s, Critical Path: 5.11s
INFO: 184 processes: 184 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
//tests:bison_test                                                    NO STATUS

FAILED: Build did NOT complete successfully

**Comment by jmillikin** [comment]
I don't have access to that Docker image. This is most likely an incompatibility between gnulib and Clang, with gnulib assuming Linux builds are performed only with GNU GCC and GNU libc. From the log I can tell your failed build used Clang, and it might have been linking with musl.

I tried doing a quick `./configure && make` run with a Clang 7 docker image (https://hub.docker.com/r/conanio/clang7/), but it failed:
```
freadahead.c:92:3: error: "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on
      your system, then report this to bug-gnulib."
 #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your syst...
  ^
```

It's also possible this is a bug in Bazel's compiler configuration. I found https://bugs.llvm.org/show_bug.cgi?id=16404, which says that `undefined reference to '__muloti4'` can happen when a Clang-built binary isn't linked against the Clang runtime support library `compiler-rt`.

**Comment by renau** [comment]
That docker image is supposed to be public.

Let me know if you can not, I can try to get another that also fails. I
tried in my arch Linux machine, and it also fails to compile (different
error).

**Comment by nlopezgi** [comment]
Hi, 
rbe toolchains here for comments.
the rbe docker image is available for public download from:
`marketplace.gcr.io/google/rbe-ubuntu16-04` (requires gcloud login) or from
`l.gcr.io/google/rbe-ubuntu16-04` (does not require gcloud login)
It does come with clang installed.

@renau , In general, you should run your build with flag `--verbose_failures` to get a complete error message which would help identify why the clang command is failing. 

Note we have not seen any other bazel rules run into https://bugs.llvm.org/show_bug.cgi?id=16404 before, but the first hypothesis @jmillikin proposes might be the issue at hand (as the rbe container does not include GCC).

**Comment by jmillikin** [comment]
Thanks, I was able to pull `l.gcr.io/google/rbe-ubuntu16-04` and reproduced this error locally.

I think this is technically a bug in Clang, but working around it by patching m4's gnulib will be much easier than getting new LLVM toolchains everywhere. The bug appears to have been known in the LLVM bug tracker since at least 2013 (https://bugs.llvm.org/show_bug.cgi?id=16404).

It might be possible to work around in Bazel by adding `--rtlib=compiler-rt` to the linker options when using Clang, but in the RBE image this fails due to a missing file (see below).

Details for interested RBE toolchain engineers:
* GCC and Clang both have compiler support libraries, `libgcc_s` and `compiler-rt` respectively. These libraries define symbols for functions that the compilers may use in place of intrinsics.
* On Linux, Clang links against `libgcc_s` inststead of `compiler-rt`. This mostly works, but fails in cases where Clang emits a call to a support function that doesn't exist in `libgcc_s`.
* Clang's implementation of [`__builtin_mul_overflow()`](https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html) emits a call to `__muloti4()`, which doesn't exist in `libgcc_s`.
* `m4/lib/xalloc-oversized.h` has an optimized path for Clang that calls `__builtin_mul_overflow()`, thus inserting calls to the missing functions.

Test case:

```c
#include <stddef.h>
void xalloc_oversized(size_t n, size_t s) {
  ptrdiff_t res;
  __builtin_mul_overflow(n, s, &res);
}
int main() { return 0; }
```

Output:

```
$ clang undef.c
/tmp/undef-8e9944.o: In function `xalloc_oversized':
undef.c:(.text+0x31): undefined reference to `__muloti4'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)

$ clang --rtlib=compiler-rt undef.c
/usr/bin/ld: cannot find /usr/local/lib/clang/8.0.0/lib/linux/libclang_rt.builtins-x86_64.a: No such file or directory
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jmillikin** [comment]
OK, I've pushed a fix to rules_m4, and updated rules_bison's example workspace. You'll want to update your workspace to pull rules_m4 at current HEAD (ae19f8df57f680c6dbad4887e162ca17ee97a13e).
